### ISSUE TITLE
テンプレートtheadのlabelへ関数を設定すると、フィルタダイアログに関数自体が表示されてしまう

### ISSUE THREAD

**Issue by hide1010** [kazuhikoarase/comfortable-js#10]
theadのlabelへ関数を設定すると、フィルタダイアログに関数自体が表示されてしまう現象があります。

下記のようなテンプレートを設定。
```
thead: [
  [
    { 
      label: '',
      dataField: 'test1' 
    },
    {
      label() {
        return 'test2'
      },
      dataField: 'test2'
    }
  ]
```

フィルタダイアログ で　下記のように表示されてしまいますが、
```
"function label() { return 'test2'; }" からフィルターをクリア
```
Function である場合、下記のように実行結果が表示されることを期待します。
```
test2 からフィルターをクリア
```

ご検討お願いいたします。

**Comment by kazuhikoarase** [comment]
Hi,

I fixed it and published to npmjs.

Thank you for your reporting.

https://jsfiddle.net/mjp7c64h/2/

**Comment by hide1010** [comment]
早速の対応頂きありがとうございます。
フィルタダイアログの方は確認できたのですが、
テキストフィルタでオープンされる、
「テキストフィルタダイアログ」では、関数のまま表示されてしまっています。
こちらも同様にご対応いただけないでしょうか。
ご検討よろしくお願いたします。

**Comment by kazuhikoarase** [comment]
I did it. Thanks again.

https://jsfiddle.net/8e5jg93s/1/

**Comment by hide1010** [comment]
改善されました。
迅速に対応していただきありがとうございます。
